pipeline {
    agent any
    tools { nodejs 'node20' }
    environment {
        SONAR_SERVER  = 'SonarQube'
        SONAR_TOKEN   = credentials('sonarqube-token')
        IMAGE         = 'parkontrol-backend'
        CONTAINER     = 'parkontrol-api'
        PORT_HOST     = '8000'
        PORT_APP      = '3000'
    }
    stages {
        // --- ESTA ETAPA ES LA QUE FALTA ---
        stage('Checkout') {
            steps {
                // Reemplaza la URL con la de tu repositorio de GitHub
                git branch: 'main', url: 'https://github.com/valenguz/parkontrol_web-main.git'
            }
        }

        stage('Install') {
            steps { 
                dir('backend') { 
                    sh 'npm install' 
                } 
            }
        }

        stage('Test') {
            steps { 
                dir('backend') { 
                    sh 'npm run test:cov' 
                } 
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('backend') {
                    withSonarQubeEnv("${SONAR_SERVER}") {
                        sh "npx sonar-scanner -Dsonar.projectKey=park-be -Dsonar.token=${SONAR_TOKEN}"
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps { 
                timeout(time: 5, unit: 'MINUTES') { 
                    waitForQualityGate abortPipeline: true 
                } 
            }
        }

        stage('Docker Build') {
            steps {
                dir('backend') {
                    sh "docker build -t ${IMAGE}:latest ."
                }
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    docker stop ${CONTAINER} || true
                    docker rm ${CONTAINER} || true
                    docker run -d --name ${CONTAINER} --network devops-net -p ${PORT_HOST}:${PORT_APP} ${IMAGE}:latest
                """
            }
        }
    }
}