sonar.projectKey=parkontrol-backend
sonar.sources=src
sonar.tests=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_34901f7e9e170f1f4c8634184fa2bdbf7ea6004f

sonar.test.inclusions=**/*.integration.spec.ts

sonar.inclusions=\
src/auth/**/*.ts,\
src/celdas/**/*.ts,\
src/facturacion/**/*.ts,\
src/pagos/**/*.ts,\
src/parqueaderos/**/*.ts,\
src/reportes/**/*.ts,\
src/reservas/**/*.ts,\
src/tarifas/**/*.ts,\
src/usuarios/**/*.ts,\
src/vehiculos/**/*.ts,\
src/vistas/**/*.ts

sonar.exclusions=\
**/*.spec.ts,\
**/*.dto.ts,\
**/*.entity.ts,\
**/*.interface.ts,\
**/*.guard.ts,\
**/*.decorator.ts,\
**/*.controller.ts,\
**/*.module.ts,\
**/entities/**,\
**/dto/**,\
**/guards/**,\
**/interfaces/**,\
**/decorators/**,\
src/main.ts,\
src/seeds/**