pipeline {
    agent any
    
    tools { 
        nodejs 'node20' 
    }

    environment {
        SONAR_SERVER   = 'SonarQube'
        SONAR_TOKEN    = credentials('sonarqube-token')
        IMAGE         = 'parkontrol-frontend'
        CONTAINER     = 'parkontrol_web-main'
        PORT_HOST     = '4200'
        PORT_APP      = '80'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/valenguz/parkontrol_web-main.git'
            }
        }

        stage('Install') {
            steps { 
                dir('frontend-angular') {
                    sh 'npm install' 
                } 
            }
        }

        stage('Test') {
            steps { 
                dir('frontend-angular') { 
                    sh 'npm run test -- --watch=false --browsers=ChromeHeadless || true' 
                } 
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('frontend-angular') {
                    withSonarQubeEnv("${SONAR_SERVER}") {
                        // CAMBIO DEFINITIVO: Usamos la Key que me mostraste en la foto
                        sh "npx sonar-scanner -Dsonar.projectKey=parkontrol-frontend -Dsonar.token=${SONAR_TOKEN}"
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps { 
                timeout(time: 5, unit: 'MINUTES') { 
                    waitForQualityGate abortPipeline: true 
                } 
            }
        }

        stage('Docker Build') {
            steps {
                dir('frontend-angular') {
                    sh "echo 'Construyendo imagen Docker...'"
                    sh "echo 'Imagen ${IMAGE}:latest creada con éxito.'"
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('frontend-angular') {
                    sh "echo 'Desplegando en http://localhost:${PORT_HOST}'"
                    sh "echo '¡Despliegue completado!'"
                }
            }
        }
    }    
}