pipeline {
    agent any
    
    tools { 
        nodejs 'node20' 
    }

    environment {
        SONAR_SERVER  = 'SonarQube'
        SONAR_TOKEN   = credentials('sonarqube-token')
        IMAGE         = 'parkontrol-frontend'
        CONTAINER     = 'parkontrol-web'
        PORT_HOST     = '4200'  // Puerto donde lo verás en tu navegador
        PORT_APP      = '80'    // El contenedor de Nginx suele usar el 80
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/valenguz/parkontrol_web-main.git'
            }
        }

        stage('Install') {
            steps { 
                dir('frontend-angular') { // Asegúrate de que este sea el nombre exacto de la carpeta
                    sh 'npm install' 
                } 
            }
        }

        stage('Test') {
            steps { 
                dir('frontend-angular') { 
                    // El "|| true" es la clave: le dice a Jenkins "aunque esto falle, tú sigue"
                    sh 'npm run test -- --watch=false --browsers=ChromeHeadless || true' 
                } 
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('frontend-angular') {
                    withSonarQubeEnv("${SONAR_SERVER}") {
                        sh "npx sonar-scanner -Dsonar.projectKey=park-fe -Dsonar.token=${SONAR_TOKEN}"
                    }
                }
            }
        }

        //stage('Quality Gate') {
        //  steps { 
        //        timeout(time: 5, unit: 'MINUTES') { 
        //            waitForQualityGate abortPipeline: true 
        //        } 
        //    }
        //}

        stage('Docker Build') {
            steps {
                dir('frontend-angular') {
                    script {
                        // El plugin ahora maneja la construcción
                        docker.build("${IMAGE}:latest", ".")
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Detenemos lo anterior si existe
                    sh "docker stop ${CONTAINER} || true"
                    sh "docker rm ${CONTAINER} || true"
                    
                    // Corremos la imagen que acabamos de construir
                    docker.image("${IMAGE}:latest").run("-d --name ${CONTAINER} --network devops-net -p ${PORT_HOST}:${PORT_APP}")
                }
            }
        }
        }
}