sonar.projectKey=parkontrol-frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_1a74f87f6e4d3943702eab8963475226e5a8d408

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.inclusions=\
src/app/pages/celdas/**/*.ts,\
src/app/pages/facturacion/**/*.ts,\
src/app/pages/pagos/**/*.ts,\
src/app/pages/reservas/**/*.ts,\
src/app/pages/usuarios/**/*.ts,\
src/app/pages/vehiculos /**/*.ts,\
src/app/pages/tarifas/**/*.ts,\
src/app/pages/parqueaderos/**/*.ts,\
src/app/pages/vistas/**/*.ts

sonar.exclusions=\
src/app/components/**,\
src/app/layout/**,\
src/app/models/**,\
src/app/environments/**,\
src/app/guards/**,\
src/app/interceptors/**,\
src/app/**/*.module.ts,\
src/app/**/*.routing.ts

# Ajusta el nombre del proyecto según la carpeta que genera Karma
sonar.javascript.lcov.reportPaths=coverage/lcov.info
